version: '2'

services:
  db:
    #   Flyway 5 (comes from Spring Boot) and is automatically configured to work with Postgres 11
    #  (that's why there are not configurations in the pom.xml or in any classes)
    #   Flyway 6 (not supported yet by Spring) needs to be configured and it works with Postgres 12
    #   Flyway 5 doesn't work with Postgres 12
    #   Once the image has been pulled when the project has been created only Postgres 11 was available, and this
    #   command doesn't check the "latest" version but only if you have a version on the current machine
    image: postgres:11
    environment:
      POSTGRES_DB: objects
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: clashofclans
    ports:
      - "5432:5432"
